backend:
  name: git-gateway
  branch: main

media_folder: "_site/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "template1"
    label: "Template 1"
    folder: "/template1"
    create: true
    slug: "{{ title }}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/tem1.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Featured Image", name: "featuredImage", widget: "image" }
      - label: Widget 1
        name: widget 1
        widget: list
      fields:
        - { label: "title", name: "title", widget: "string"}
        - { label: "description", name: "description", widget: "string"}
        - { label: "widget images", name: "widgetImg", widget: "image"}
