backend:
  name: git-gateway
  branch: main

media_folder: "_site/assets/images/uploads"
public_folder: "assets/images/uploads"

collections:
  - name: "template1"
    label: "template 1"
    folder: "template1"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
    - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/tem1.njk" }
    - { label: "Title", name: "title", widget: "string", default: "CrowdComms Template One" }
    - { label: "Background Image", name: "backgroundImage", widget: "image", default: "https://media.crowdcomms.com/media/app_images/e96a6ec9a7194e138bb5fe8384f51b35.jpg?d=1920x1080" }
    - { label: "Title Logo", name: "titleLogo", widget: "image", default: "https://media.crowdcomms.com/media/app_images/78011e11e64a4c88b60b370171f38740.png" }
    - { label: "Title Description", name: "titleDescription", widget: "string", default: "Welcome to the first event in a series of awesome event co. learning sessions. This will improve the way you work with your team and enhance productivity or positivity" }
    - { label: "Title Video Poster", name: "titleVideoPoster", widget: "image", default: "https://media.crowdcomms.com/media/app_images/2ff90d785368482ea98add5c80c3f51d.jpg" }
    - { label: "Primary CTA", name: "primaryCTA", widget: "string", default: "HELPDESK" }
    - { label: "Primary CTA Description", name: "primaryCTADescription", widget: "string", default: "Need help finding your way around? \n Get in touch with one of our team"}
    - { label: "Widget Arrow", name: "widgetArrow", widget: "image", default: "https://media.crowdcomms.com/media/app_images/f63a7b49cd4d4f34b367a0ad9990deac.png" }
    - label: "Title Video"
      name: "titleVideo"
      widget: "file"
      default: "https://player.vimeo.com/external/477725158.hd.mp4?s=bb269ea949d5560afa83f8d32a420cecf75e532f&profile_id=175"
      media_library:
        config:
          multiple: false
    - label: "Widgets"
      name: "widgets"
      widget: "list"
      collapsed: false
      fields:
        - { label: "Widget Name", name: "widgetName", widget: "string" }
        - { label: "Widget Image", name: "widgetImage", widget: "image" }
      default:
        - { widgetName: "Agenda", widgetImage: "https://media.crowdcomms.com/media/app_images/7350f6ff357c4050baf911151a4e7c1b.jpg" }
        - { widgetName: "Main Stage", widgetImage: "https://media.crowdcomms.com/media/app_images/06e449b24f264868897cde5eca470e78.jpg" }
        - { widgetName: "Attendees", widgetImage: "https://media.crowdcomms.com/media/app_images/1a1733cf07ce4044ab534eea1df3e491.jpg" }
        - { widgetName: "Event Game", widgetImage: "https://media.crowdcomms.com/media/app_images/79ba227805844b2997b2804ec22d3d46.jpg" }
        - { widgetName: "Speakers", widgetImage: "https://media.crowdcomms.com/media/app_images/1b572de800f2414984d448b2a2ce3039.jpg" }
        - { widgetName: "Survey", widgetImage: "https://media.crowdcomms.com/media/app_images/5149b2968a6c4833912fcbef62ee9b8f.png" }
  - name: "template2"
    label: "template 2"
    folder: "template2"
    create: true
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}"
    fields:
    - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/tem1.njk" }
    - { label: "Background Image", name: "backgroundImage", widget: "image", default: "https://media.crowdcomms.com/media/app_images/e96a6ec9a7194e138bb5fe8384f51b35.jpg?d=1920x1080" }
    - { label: "Title Logo", name: "titleLogo", widget: "image", default: "https://media.crowdcomms.com/media/app_images/78011e11e64a4c88b60b370171f38740.png" }
    - { label: "Title Description", name: "titleDescription", widget: "string", default: "Welcome to the first event in a series of awesome event co. learning sessions. This will improve the way you work with your team and enhance productivity or positivity" }
    - { label: "Widget Arrow", name: "widgetArrow", widget: "image", default: "https://media.crowdcomms.com/media/app_images/f63a7b49cd4d4f34b367a0ad9990deac.png" }
    - label: "Widgets"
      name: "widgets"
      widget: "list"
      collapsed: false
      fields:
        - { label: "Widget Name", name: "widgetName", widget: "string" }
        - { label: "Widget Description", name: "widgetDescription", widget: "string" }
        - { label: "Widget Image", name: "widgetImage", widget: "image" }
      default:
        - { widgetName: "Feedback Survey", widgetDescription: "Let us know how we did", widgetImage: "https://media.crowdcomms.com/media/app_images/a0ba8cfd55b04ebda768f5de9c6c47ae.jpg" }
        - { widgetName: Agenda, widgetDescription: Find out what's on, when. Sign up to sessions and build your personal session plan, widgetImage: https://media.crowdcomms.com/media/app_images/acbc8d7cd84c4f14af5530b7634c7aa0.jpg }
        - { widgetName: Main Stage, widgetDescription: Streaming live from the event!, widgetImage: https://media.crowdcomms.com/media/app_images/1c3c76374e624dba9650ac59b6c004f9.jpg }
        - { widgetName: Networking, widgetDescription: Who's around? Enjoy the event together, widgetImage: https://media.crowdcomms.com/media/app_images/fd1ad25b63c44cc786acc029c43f1c91.jpg }
        - { widgetName: Event Game, widgetDescription: Have you got what it takes to be the best?., widgetImage: https://media.crowdcomms.com/media/app_images/a25208de0665448b94ee1cf4995a99f3.jpg }
        - { widgetName: Speakers, widgetDescription: View speaker profiles, widgetImage: https://media.crowdcomms.com/media/app_images/e77c21bf14f14fca8448d1321bee450e.jpg }