backend:
  name: git-gateway
  branch: main
media_folder: "_site/assets/images/uploads"
public_folder: "assets/images/uploads"

collections:
  - name: "template1"
    label: "template1"
    folder: "/template1"
    create: true
    slug: "{{title}}"
    fields:
    - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/tem1.njk" }
    - { label: "Title", name: "layout", widget: "string" }
    - { label: "Background Image", name: "backgroundImage", widget: "image" }
    - { label: "Title Logo", name: "titleLogo", widget: "image" }
    - { label: "Title Description", name: "titleDescription", widget: "string" }
    - { label: "Title Video Poster", name: "titleVideoPoster", widget: "image" }
    - { label: "Title Video Poster", name: "titleVideoPoster", widget: "image" }
    - { label: "Primary CTA", name: "primaryCTA", widget: "string" }
    - { label: "Primary CTA Description", name: "primaryCTADescription", widget: "string" }
    - { label: "Widget Arrow", name: "widgetArrow", widget: "image" }
    - label: "Title Video"
      name: "titleVideo"
      widget: "file"
      default: "https://player.vimeo.com/external/477725158.hd.mp4?s=bb269ea949d5560afa83f8d32a420cecf75e532f&profile_id=175"
      media_library:
        config:
          multiple: false
    - label: "Widgets"
      name: "widgets"
      widget: "list"
      collapsed: false
      fields:
        - { label: "Widget Name", name: "widgetName", widget: "string" }
        - { label: "Widget Image", name: "widgetImage", widget: "image" }
      default:
        - { widgetName: "Agenda", widgetImage: "https://media.crowdcomms.com/media/app_images/7350f6ff357c4050baf911151a4e7c1b.jpg" }
        - { widgetName: "Main Stage", widgetImage: "https://media.crowdcomms.com/media/app_images/06e449b24f264868897cde5eca470e78.jpg" }
        - { widgetName: "Attendees", widgetImage: "https://media.crowdcomms.com/media/app_images/1a1733cf07ce4044ab534eea1df3e491.jpg" }
        - { widgetName: "Event Game", widgetImage: "https://media.crowdcomms.com/media/app_images/79ba227805844b2997b2804ec22d3d46.jpg" }
        - { widgetName: "Speakers", widgetImage: "https://media.crowdcomms.com/media/app_images/1b572de800f2414984d448b2a2ce3039.jpg" }
        - { widgetName: "Survey", widgetImage: "https://media.crowdcomms.com/media/app_images/5149b2968a6c4833912fcbef62ee9b8f.png" }